# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import yield_from as yield_from_module
import typed_ast.ast3 as typed_ast_module

def test_visit_with_none_node_does_not_raise():
    # Setup: Create a YieldFromTransformer instance with a None node.
    # The constructor receives None as the root AST node to be transformed.
    none_node = None
    yield_from_transformer = yield_from_module.YieldFromTransformer(none_node)

    # Execution: Attempt to visit the None node.
    # This exercises the visit method, which internally calls
    # _handle_assignments, _handle_expressions, and generic_visit.
    result = yield_from_transformer.visit(none_node)

    # Assertion: Visiting a None node should not raise an exception.
    # The method is expected to complete without error when given None.
    assert result is None

def test_yield_from_transformer_initialization_stores_context():
    # Setup: Prepare the context (None in this case) that the transformer
    # should hold internally after construction.
    transformer_context = None

    # Execution: Instantiate the YieldFromTransformer with the given context.
    transformer = yield_from_module.YieldFromTransformer(transformer_context)

    # Assertion: Verify the transformer was created successfully.
    # A successfully initialized transformer should not be None.
    assert transformer is not None

def test_yield_from_transformer_visits_while_node_with_empty_suites():
    # Setup
    transformer_instance = yield_from_module.YieldFromTransformer(None)
    empty_suite = [None, None]
    while_node_ast_fields = [empty_suite, empty_suite]
    while_node = typed_ast_module.While(*while_node_ast_fields)

    # Execution
    transformed_node = transformer_instance.visit(while_node)

    # Assertion
    assert transformed_node is not None

def test_yield_from_transformer_visit_while_statement_produces_valid_ast_node():
    # Setup: create a YieldFromTransformer instance with a None context
    yield_from_transformer = yield_from_module.YieldFromTransformer(None)

    # Setup: build a While AST node with a None test/body and keyword args provided via dict
    none_value = None
    while_test_and_body = [none_value, none_value]
    keyword_argument_name = "P+>W*v\nDN{M8\x0bLk"
    while_keyword_arguments = {
        keyword_argument_name: yield_from_transformer,
        keyword_argument_name: yield_from_transformer,
        keyword_argument_name: yield_from_transformer,
    }
    while_statement_node = typed_ast_module.While(
        *while_test_and_body, **while_keyword_arguments
    )

    # Execution: visit the While node with the transformer
    visited_node = yield_from_transformer.visit(while_statement_node)

    # Assertion: the visit should return an AST node (not raise, and produce a result)
    assert isinstance(visited_node, typed_ast_module.AST)

