import pytest
import re as regex
import helpers as helpers

def test_debug_with_purge_message():
    # Test that debug function can accept and process a message
    # generated by purge() without raising any exceptions

    # Setup: Generate a purge message using module_0's purge function
    purge_message = module_0.purge()

    # Execute: Pass the purge message to the debug function
    # debug() should handle the callable message without errors
    result = module_1.debug(purge_message)

    # Assert: debug() returns None as it only prints to stderr when debug mode is enabled
    assert result is None

def test_variables_generator_instantiation():
    # Test that VariablesGenerator can be successfully instantiated
    # This verifies the basic constructor works without errors

    # Setup & Execution: Create a new VariablesGenerator instance
    variables_generator = module_1.VariablesGenerator()

    # Assert: Verify the instance was created successfully
    assert variables_generator is not None

def test_eager_wraps_variables_generator_returning_list():
    # Test that eager() wraps a VariablesGenerator callable and returns a List type wrapper
    # The eager decorator should convert any iterable-returning function into a list-returning function

    # Setup: Create a VariablesGenerator instance to be wrapped by eager
    variables_generator = module_1.VariablesGenerator()

    # Execute: Apply the eager decorator to the VariablesGenerator instance
    eager_wrapped_generator = module_1.eager(variables_generator)

    # Assert: Verify that the eager wrapper is callable and has been successfully created
    assert callable(eager_wrapped_generator), (
        "eager() should return a callable that wraps the original VariablesGenerator"
    )

def test_eager_wraps_callable_and_supports_debug_warn_get_source():
    """
    Test that the `eager` function correctly wraps a callable (including an integer-wrapped callable),
    and that `debug`, `warn`, and `get_source` can be called on these wrapped functions
    without raising errors.
    """
    # Constants
    INITIAL_VALUE = 939

    # Setup: Create an eager-wrapped callable from an integer value
    eager_wrapped_callable = module_1.eager(INITIAL_VALUE)

    # Setup: Create a VariablesGenerator instance (verifying instantiation works alongside these calls)
    variables_generator = module_1.VariablesGenerator()

    # Execution: Call debug with the eager-wrapped callable as the message provider
    debug_result = module_1.debug(eager_wrapped_callable)

    # Execution: Wrap the already-eager callable again with eager
    double_eager_wrapped_callable = module_1.eager(eager_wrapped_callable)

    # Execution: Call warn with the initial integer value as the message
    warn_result = module_1.warn(INITIAL_VALUE)

    # Execution & Assertion: Retrieve source code of the eager-wrapped callable
    # Verifies that get_source can inspect the wrapped function without raising errors
    module_1.get_source(eager_wrapped_callable)

    # Assert: debug and warn return None as expected
    assert debug_result is None
    assert warn_result is None

def test_warn_with_proxy_handler_message():
    # Test that the warn function correctly handles a warning message
    # and returns None when called with a valid string message
    
    # Setup
    PROXY_HANDLER_MESSAGE = "ProxyHandler"
    
    # Execute
    warn_result = module_1.warn(PROXY_HANDLER_MESSAGE)
    
    # Assert
    # The warn function should return None as it only prints to stderr
    assert warn_result is None

def test_eager_decorator_with_non_callable_argument():
    """
    Test that the eager decorator raises an error when called with a non-callable
    argument (integer) as the function to wrap, and then attempts to invoke
    the resulting wrapped function with itself as arguments and None as the module.
    """
    # Setup
    NON_CALLABLE_VALUE = 939
    MODULE_VALUE = None

    # Execution & Assertion
    # eager expects a callable, but receives an integer (939)
    # this should raise a TypeError when the wrapped function tries to call the integer
    eager_wrapped = module_1.eager(NON_CALLABLE_VALUE)

    with pytest.raises((TypeError, Exception)):
        # Attempt to call the wrapped result with itself as positional and keyword arguments
        eager_wrapped.__call__(eager_wrapped, eager_wrapped, module=MODULE_VALUE, start=eager_wrapped)

