# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import cmd as command_handler

def test_build_setup_cfg_command_class_works_with_valid_setup_command_config():
    """
    Tests that the build_setup_cfg_command_class method works correctly
    when providing a valid SetupCfgCommandConfig object. It should return
    a type, where the name, description, commands, and user_options properties
    are set as expected.
    """

    # Constants
    NAME = 'test'
    DESCRIPTION = 'Test command'
    COMMANDS = ('test',)

    # Setup
    command_setup_config = command_handler.SetupCfgCommandConfig(NAME, DESCRIPTION, COMMANDS)

    # Execution
    command_class = command_handler.build_setup_cfg_command_class(command_setup_config)

    # Assertion
    assert command_class.name == NAME
    assert command_class.description == DESCRIPTION
    assert command_class.commands == COMMANDS
    assert isinstance(command_class.user_options, list)  # Can be any list of strings.

