# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import typed_ast.ast3 as module_ast3
import pytest

def test_module_ast3_dump_none_object():
    NONE_OBJECT = None
    none_type = NONE_OBJECT

    with pytest.raises(Exception):
        module_ast3.dump(none_type)

    assert False, "Dumping a None object should raise an exception!"

