# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import immutable_list as immutable_list

import immutable_list

def test_immutable_list_equality1():
    # Setup
    empty_list = immutable_list.ImmutableList()

    # Execution
    is_equal = empty_list == empty_list

    # Assertion
    assert is_equal, "The lists should be equal because they are the same instance"


def test_immutable_list_to_str1():
    # Setup
    empty_list = immutable_list.ImmutableList()

    # Execution
    str_representation = str(empty_list)

    # Assertion
    assert str_representation == 'ImmutableList[]', "The string representation should be 'ImmutableList[]'"


def test_immutable_list_to_list1():
    # Setup
    empty_list = immutable_list.ImmutableList()

    # Execution
    list_representation = empty_list.to_list()

    # Assertion
    assert list_representation == [], "The to_list method should return an empty list"


def test_immutable_list_add_empty1():
    # Setup
    empty_list = immutable_list.ImmutableList()
    another_empty_list = immutable_list.ImmutableList()

    # Execution
    result = empty_list + another_empty_list

    # Assertion
    assert result.to_list() == [], "Adding two empty lists should result in an empty list"


def test_immutable_list_len1():
    # Setup
    empty_list = immutable_list.ImmutableList()

    # Execution
    length = len(empty_list)

    # Assertion
    assert length == 0, "The length of an empty list should be 0"

def test_immutable_list_unsupported_concat():
    ELEMENT = 7
    EMPTY_LIST = ImmutableList()
    with pytest.raises(ValueError):
        EMPTY_LIST + ELEMENT

def test_immutable_list_equality():
    LIST = ImmutableList(1, 2, 3, 4, 5)
    assert LIST == LIST

def test_immutable_list_inequality():
    LIST = ImmutableList(1, 2, 3, 4, 5)
    EMPTY_LIST = ImmutableList()
    assert LIST != EMPTY_LIST

def test_immutable_list_to_str():
    LIST = ImmutableList(1, 2, 3, 4, 5)
    assert str(LIST) == 'ImmutableList[1, 2, 3, 4, 5]'

def test_immutable_list_find():
    FUNCTION = lambda x: x % 2 == 0
    LIST = ImmutableList(1, 2, 3, 4, 5)
    assert LIST.find(FUNCTION) == 2

def test_immutable_list_add_empty():
    LIST = ImmutableList(1, 2, 3, 4, 5)
    EMPTY_LIST = ImmutableList()
    assert (LIST + EMPTY_LIST) == LIST

def test_immutable_list_unshift():
    ELEMENT = 7
    LIST = ImmutableList(1, 2, 3, 4, 5)
    assert LIST.unshift(ELEMENT).head == ELEMENT
    assert LIST.unshift(ELEMENT).tail == LIST

def test_immutable_list_reduce():
    LIST = ImmutableList(1, 2, 3, 4, 5)
    assert LIST.reduce(lambda x, y: x + y, 0) == 15

def test_immutable_list_find_element():
    # Constants
    FIRST_ELEMENT = True
    SECOND_ELEMENT = False

    # Setup
    immutable_list = immutable_list_module.ImmutableList(FIRST_ELEMENT, is_empty=FIRST_ELEMENT)
    expected_result = immutable_list_module.ImmutableList(SECOND_ELEMENT, FIRST_ELEMENT, is_empty=FIRST_ELEMENT)

    # Execution
    actual_result = immutable_list.append(SECOND_ELEMENT)

    # Assertion
    assert actual_result == expected_result, f"Expected {expected_result} but found {actual_result}"
    assert actual_result.find(lambda n: n is True) == FIRST_ELEMENT, "Failed to find the first element in ImmutableList"

def test_adding_immutable_list_to_immutable_list():
    # GIVEN an empty immutable list
    empty_list = immutable_list.ImmutableList()

    # WHEN adding another empty list
    result = empty_list.__add__(immutable_list.ImmutableList())

    # THEN verify the resulting list is also empty
    assert result.is_empty(), "The resulting list should be empty"

    # AND that the lists are different instances
    assert result is not empty_list, "The original and resulting lists should be different instances"

    # GIVEN an immutable list with one element
    list_with_one_element = immutable_list.ImmutableList(10)

    # WHEN adding another empty list
    result = list_with_one_element.__add__(immutable_list.ImmutableList())

    # THEN verify the resulting list has the same elements
    assert result == immutable_list.ImmutableList(10), "The resulting list should have the same elements"

    # AND that the lists are different instances
    assert result is not list_with_one_element, "The original and resulting lists should be different instances"

    # GIVEN an immutable list with multiple elements
    list_with_multiple_elements = immutable_list.ImmutableList(10, 20, 30)

    # WHEN adding another list with multiple elements
    result = list_with_multiple_elements.__add__(immutable_list.ImmutableList(40, 50))

    # THEN verify the resulting list has all the elements
    assert result == immutable_list.ImmutableList(10, 20, 30, 40, 50), "The resulting list should have all the elements"

    # AND that the lists are different instances
    assert result is not list_with_multiple_elements, "The original and resulting lists should be different instances"

def test_find_element_in_empty_immutable_list():
    # Constants for input values
    EMPTY_LIST = immutable_list.ImmutableList()
    EXPECTED_RESULT = None

    # Setup
    my_list = EMPTY_LIST

    # Execution
    result = my_list.find(is_even)  # 'is_even' is a placeholder function, it needs to be replaced

    # Assertion
    assert result == EXPECTED_RESULT, f"Expected {EXPECTED_RESULT}, but got {result}"

def test_find_element_in_non_empty_immutable_list():
    # Constants for input values
    NON_EMPTY_LIST = immutable_list.ImmutableList(1, 2, 3, 4, is_empty=False)
    EXPECTED_RESULT = 2

    # Setup
    my_list = NON_EMPTY_LIST

    # Execution
    result = my_list.find(is_even)  # 'is_even' is a placeholder function, it needs to be replaced

    # Assertion
    assert result == EXPECTED_RESULT, f"Expected {EXPECTED_RESULT}, but got {result}"

# Helper function for testing find method
def is_even(n):
    return n % 2 == 0

def test_immutable_list_find_method():
    # Constants
    TREATED_NULL_VALUE = None

    # Setup
    EMPTY_IMMUTABLE_LIST = immutable_list.ImmutableList(TREATED_NULL_VALUE, is_empty=True)

    # A function to be used for the purpose of the test
    def check_element(el):
        # a function that simply returns True for every input
        return True

    # Execution and Assertion
    # Chekcing the __len__() method return value
    assert 0 == len(EMPTY_IMMUTABLE_LIST)

    # Trying to find an element that meets the criteria in the check_element function
    # As the ImmutableList is empty, None is expected to be returned
    assert TREATED_NULL_VALUE == EMPTY_IMMUTABLE_LIST.find(check_element)

# Renamed: test_immutable_list_find_method -> test_finds_none_when_list_is_empty
def test_finds_none_when_list_is_empty():
    # Create an empty immutable list
    my_list = immutable_list.ImmutableList()
    # Define a function that always returns False
    def always_false(some_value):
        return False
    # Check if `find` method returns None when called with our predicate on an empty list
    assert my_list.find(always_false) is None, "Expected find method to return None for an empty list"
    
# Renamed: test_find_element_in_non_empty_immutable_list -> test_finds_element_in_list
def test_finds_element_in_list():
    # Create an immutable list with some elements
    elements = [1, 2, 3, 4, 5]
    my_list = immutable_list.ImmutableList(elements)
    # Define a function that checks if any number is even
    def is_even(element):
        return element % 2 == 0
    # Check if the `find` method returns an even number in the list
    assert my_list.find(is_even) in [2, 4], "Expected find method to find even number in the list"

# Renamed: test_adding_immutable_list_to_immutable_list -> test_to_list_conversion
def test_to_list_conversion():
    # Create an immutable list with some elements
    elements = [1, 2, 3]
    my_list = immutable_list.ImmutableList(elements)
    # Expected list after conversion
    expected_list = [1, 2, 3]
    # Convert the list to a regular Python list and check
    assert my_list.to_list() == expected_list, "Expected to_list method to correctly convert the list to a Python list"

def test_append_and_find_then_to_list():
    # Test Constants
    NO_ELEMENT = None
    SAMPLE_ITEMS = [1, 2, 3, 4, 5]

    # Test Setup
    immutable_list = module_0.ImmutableList()

    # Test Execution and Assertion
    for item in SAMPLE_ITEMS:
        immutable_list = immutable_list.append(item)
        assert immutable_list.find(lambda x: x == item) == item

    assert immutable_list.to_list() == SAMPLE_ITEMS

    # Extra Assertion
    assert immutable_list.find(lambda x: x == NO_ELEMENT) is None

def test_map_function_applies_function_to_all_elements():
    """
    This test case is designed to verify that the map function correctly applies the provided function to all elements in the ImmutableList.

    Setup:
    1- Created an empty ImmutableList.

    Execution:
    2- Used the map function to apply another function that reverses the string representation of all list elements.
    3- Converted the modified ImmutableList back to a list.

    Assertion:
    4- Verified that the resultant list contains the reversed string representations of all elements from the original list.
    """

    EMPTY_IMMUTABLE_LIST = immutable_list.ImmutableList(is_empty=True)
    LIST_ELEMENTS = ['123', '456', '789']
    REVERSE_STRING = lambda x: x[::-1]

    immutable_list_ = EMPTY_IMMUTABLE_LIST
    for element in LIST_ELEMENTS:
        immutable_list_ = immutable_list.ImmutableList(element, immutable_list_)

    modified_immutable_list = immutable_list_.map(REVERSE_STRING)
    modified_list = modified_immutable_list.to_list()

    assert modified_list == list(map(REVERSE_STRING, LIST_ELEMENTS))

def test_unshift_and_append_and_map_a_new_element():
    # Constant for None argument
    NONE = None

    # Setup
    immutable_list_0 = immutable_list.ImmutableList(NONE, NONE)

    # Execution: unshifting a new element
    immutable_list_1 = immutable_list_0.unshift(NONE)
    immutable_list_2 = immutable_list_0.unshift(immutable_list_1)

    # Execution: appending a new element
    immutable_list_3 = immutable_list_1.append(NONE)

    # Execution: mapping the list
    # Note: The mapped list is discarded as there is no usecase for it in this test case
    # However, it could be used as a future assertion
    immutable_list_3.map(NONE)

    # Assertion: assert the list contains NONE
    assert NONE in immutable_list_3

def test_immutable_list_filter_with_valid_input():
    """
    Test case to verify that the filter function correctly filters the elements
    of an ImmutableList based on a given function.
    """
    # Setup - Create an instance of ImmutableList with some boolean values
    is_empty = False
    initial_values = [True, False, True, False]
    immutable_list = immutable_list.ImmutableList(initial_values, is_empty=is_empty)

    # Execution - Call the filter function on the list, filtering out the False values
    def filter_func(value: bool) -> bool:
        return value

    filtered_list = immutable_list.filter(filter_func)

    # Assertion - Check that the filtered list only contains the True values
    for value in filtered_list:
        assert value
    assert len(filtered_list) == 2

def test_filter_elements_with_length_leq_one():
    # Given: An instance of ImmutableList
    immutable_list = immutable_list_module.ImmutableList()
    # and: Adding the list to itself to create a list with one element
    immutable_list = immutable_list.__add__(immutable_list)

    # When: We filter the list to only include elements with length less than or equal to one
    filtered_list = immutable_list.filter(lambda element: len(element) <= 1)

    # Then: The filtered list should only include elements with length less than or equal to one
    assert all(len(element) <= 1 for element in filtered_list)

def test_immutable_list_find_nonexistent_in_empty_list():
    # Arrange
    TEN_K = 10000
    EMPTY_LIST = immutable_list.ImmutableList(None, None)

    def is_greater_than_ten_k(x):
        return x > TEN_K

    # Act
    element = EMPTY_LIST.find(is_greater_than_ten_k)

    # Assert
    assert element is None, "Expected to find no element that satisfies the find predicate in the empty list"

def test_find_item_when_present_in_list():
    """
    Test the find method of ImmutableList.
    This test case will check the find method when an item is present in the list. 
    We will use the find method to find the first element in the list that
    satisfies the provided function. In this case, we are finding the
    first value in the list equal to the value at index 0.
    """
    # Constants
    TEST_LIST_LENGTH = 3

    # Set up
    # Create an ImmutableList with values 0, 1, 1
    test_list = immutable_list.ImmutableList(
        TEST_LIST_LENGTH, is_empty=bool_0
    )

    target_element = 0
    check_value_for_equality = test_list.get_element_at_index(target_element)

    # Execution:
    # Call the find method, searching for the first value that is equal to the 
    # value at index 0 in the test_list
    found_element = test_list.find(lambda x: x == check_value_for_equality)

    # Assertion
    # Check that the value returned by the find method is equal to the expected value
    assert found_element == check_value_for_equality, (
        "find method did not return the correct element.")

def test_immutable_list_find_reduce():
    # Constants
    TEST_ELEMENT = False
    TEST_IS_EMPTY = True

    # Setup 
    initial_list = immutable_list.ImmutableList() # An empty list
    
    # Execute the 'find' and 'reduce' methods
    result_reduce = initial_list.reduce(TEST_ELEMENT, initial_list)
    new_list = immutable_list.ImmutableList(TEST_ELEMENT, is_empty=TEST_IS_EMPTY)
    result_find = new_list.find(new_list)
    
    # Assertion 
    # Expected result should be None 
    # Since we are trying to find element in empty list 
    assert result_find is None 
    # The reduce method should also return the default value provided (bool_0)
    assert result_reduce == TEST_ELEMENT

def test_import_of_immutableList_and_verify_if_it_is_empty():
    # Constants
    SIZE_LIST_ZERO = 0

    # Create an instance of ImmutableList
    immutable_list_0 = immutable_list.ImmutableList()

    # Get the size of the ArrayList
    result = immutable_list_0.size()

    # Check if the size of the ArrayList is 0
    assert result == SIZE_LIST_ZERO

@pytest.fixture
def get_empty_immutable_list():
    empty_list = immutable_list.ImmutableList()
    return empty_list

def test_immutable_list_find_method_success():
    """
    Test case to check the find method of ImmutableList

    Given an instance of ImmutableList, check if the find method
    returns the first element that satisfies the provided function fn.
    """

    # Constants
    MY_CONSTANT_BOOL = False  # A constant boolean value

    # Test Setup
    test_list = immutable_list.ImmutableList(MY_CONSTANT_BOOL, is_empty=MY_CONSTANT_BOOL)

    # Test Execution
    result = test_list.find(lambda x: x is MY_CONSTANT_BOOL)

    # Test Assertion
    assert result == MY_CONSTANT_BOOL, "Expected value not found in the list"

    # Clean up (if necessary)
    # ...

def test_find_in_non_empty_list():
    EMPTY_LIST = immutable_list.ImmutableList(None, is_empty=True)
    NON_EMPTY_LIST = immutable_list.ImmutableList("element", is_empty=False)

    def is_element(value):
        return value == "element"

    non_empty_list = immutable_list.ImmutableList(NON_EMPTY_LIST, is_empty=EMPTY_LIST)

    result = non_empty_list.find(is_element)
    assert result == "element", "Test case should return an element that passed the function."

def test_push_and_append_and_find_new():
    # Given
    NUM_ZERO = 0
    empty_list = immutable_list.ImmutableList(is_empty=True)

    # When a new element is unshifted on to the empty list
    result_list = empty_list.unshift(NUM_ZERO)

    # Then the resulting list should have one element
    assert len(result_list) == 1

    # And the first element of the resulting list should be NUM_ZERO
    assert result_list[0] == NUM_ZERO

    # When a new element is appended to the end of the result_list
    further_result_list = result_list.append(result_list)

    # Then the further_result_list should have two elements
    assert len(further_result_list) == 2

    # And the last element of the further_result_list should also be NUM_ZERO
    assert further_result_list[1] == NUM_ZERO

    # When we use the find method in further_result_list to find an element that matches NUM_ZERO
    # Then the first matching element should be NUM_ZERO
    assert further_result_list.find(lambda x: x == NUM_ZERO) == NUM_ZERO

    # Similarly, all elements of further_result_list should be NUM_ZERO
    assert all(element == NUM_ZERO for element in further_result_list)

def test_immutability_and_appending_to_list():
    # SETUP
    is_empty = True

    # empty list
    my_list = immutable_list.ImmutableList(None, is_empty=is_empty)

    # element to append
    element_to_append = True
    my_list = my_list.append(element_to_append)

    # EXECUTION
    length_of_list = len(my_list)

    # ASSERTION
    assert length_of_list == 1
    assert my_list.find(lambda x: x == element_to_append) == element_to_append

def test_immutable_list_operations_updated():
    """
    This test case checks the functionality of the ImmutableList
    class. It creates a new instance of ImmutableList, appends, 
    reduces, checks for equality, and adds elements to the unshift
    of another instance of ImmutableList. It then checks if an 
    empty instance of ImmutableList is equivalent to an empty 
    instance of ImmutableList. The instance is then used to find
    a certain value. Finally, the ImmutableList object is converted
    to a string and printed.
    """

    # Setup: Create initial instances of ImmutableList
    immutable_list_0 = ImmutableList()
    immutable_list_1 = immutable_list_0.append(immutable_list_0)

    # Execution: Perform operations on ImmutableLists
    var_0 = immutable_list_0.reduce(immutable_list_1, immutable_list_1)
    bool_0 = immutable_list_1.__eq__(immutable_list_0)
    immutable_list_2 = immutable_list_1.unshift(immutable_list_1)
    str_0 = immutable_list_2.__str__()
    immutable_list_3 = ImmutableList(is_empty=str_0)
    immutable_list_4 = var_0.append(var_0)

    # Assertion: Verify the result of the operations
    assert bool_0 == False
    assert immutable_list_2.find(var_0) == var_0
    assert immutable_list_0.is_empty == immutable_list_3.is_empty

def test_reduce_function_executes_correctly():
    # Setup
    EMPTY_LIST = immutable_list.ImmutableList()
    INITIAL_ELEMENT = immutable_list.ImmutableList()
    immutable_list_0 = immutable_list.ImmutableList(INITIAL_ELEMENT, EMPTY_LIST)

    # Execution
    immutable_list_1 = immutable_list_0.unshift(INITIAL_ELEMENT)
    var_0 = immutable_list_0.reduce(immutable_list_1, immutable_list_1)
    list_length = immutable_list_1.__len__()
    immutable_list_2 = immutable_list_1.unshift(immutable_list_1)
    bool_0 = immutable_list_2.__eq__(immutable_list_0)
    var_1 = immutable_list_2.find(lambda x: x % 2 == 0)

    # Assertion
    assert EMPTY_LIST == immutable_list_0, "List should be empty initially"
    assert var_0 is not None, "reduce function must not return None"
    assert list_length == 2, "Length of the list should be 2 after unshift"
    assert not bool_0, "Lists should not be equal"
    assert var_1 is None, "No even number in the list"

def test_to_list_creates_correct_list_on_single_item_immutable_list():
    # Constants
    bool_value = True
    initial_dictionary = {}

    # Setup
    single_item_immutable_list = immutable_list.ImmutableList(head=bool_value, is_empty=bool_value)

    # Execution
    result = single_item_immutable_list.to_list()

    # Assertion
    assert result == [bool_value]

def test_reduce_accumulates_fn_application_on_single_item_immutable_list():
    # Constants
    bool_value = True
    initial_dictionary = {}
    identity_function = lambda x, y: x  # This function just returns the first argument

    # Setup
    single_item_immutable_list = immutable_list.ImmutableList(head=bool_value, is_empty=bool_value)

    # Execution
    result = single_item_immutable_list.reduce(identity_function, bool_value)

    # Assertion
    assert result == bool_value

